// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxXXv8Supuel7ijaJkQooj-Q3gY9yfZ0',
    appId: '1:173310908835:web:ca7cc7b969f76ae416e216',
    messagingSenderId: '173310908835',
    projectId: 'k-s-binu-associates',
    authDomain: 'k-s-binu-associates.firebaseapp.com',
    storageBucket: 'k-s-binu-associates.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgvqWkvugjadmHLSmZyrRMnca8qWMC-w',
    appId: '1:173310908835:android:9944043d7ddd5ee816e216',
    messagingSenderId: '173310908835',
    projectId: 'k-s-binu-associates',
    storageBucket: 'k-s-binu-associates.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHv0EmJ54qVxB0-OB8tFaSPhw4izBJ9A4',
    appId: '1:173310908835:ios:410cddcc3ff8bc0316e216',
    messagingSenderId: '173310908835',
    projectId: 'k-s-binu-associates',
    storageBucket: 'k-s-binu-associates.appspot.com',
    iosBundleId: 'com.example.advKsBinuAssosciates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHv0EmJ54qVxB0-OB8tFaSPhw4izBJ9A4',
    appId: '1:173310908835:ios:ea4a7f26e4586d7016e216',
    messagingSenderId: '173310908835',
    projectId: 'k-s-binu-associates',
    storageBucket: 'k-s-binu-associates.appspot.com',
    iosBundleId: 'com.example.advKsBinuAssosciates.RunnerTests',
  );
}
